package com.outtatech.client;

/**
 * Version-latenightpizzaparty
 *
 * @author Thomas
 */
public class IntroScreen extends javax.swing.JFrame
{

    GUIController controller;

    /**
     * Version-latenightpizzaparty
     * Creates new form IntroScreen
     */
    public IntroScreen()
    {
        initComponents();
    }

    /**
     * Version-latenightpizzaparty
     * Alternate constructor to take a GUIController in
     *
     * @param ctrl method parameter
     */
    public IntroScreen(GUIController ctrl)
    {
        //set controller to ctrl
        controller = ctrl;
        initComponents();
    }

    /**
     * Version-latenightpizzaparty
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SinglePlayerButton = new javax.swing.JButton();
        MultiPlayerButton = new javax.swing.JButton();
        InformationButton = new javax.swing.JButton();
        OptionsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("INDICATION");

        jLabel2.setText("An OutaTech Game");

        SinglePlayerButton.setText("Single Player");
        SinglePlayerButton.setMaximumSize(new java.awt.Dimension(120, 23));
        SinglePlayerButton.setMinimumSize(new java.awt.Dimension(120, 23));
        SinglePlayerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SinglePlayerButtonMouseClicked(evt);
            }
        });

        MultiPlayerButton.setText("Multiplayer");
        MultiPlayerButton.setMaximumSize(new java.awt.Dimension(120, 23));
        MultiPlayerButton.setMinimumSize(new java.awt.Dimension(120, 23));
        MultiPlayerButton.setPreferredSize(new java.awt.Dimension(93, 23));
        MultiPlayerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MultiPlayerButtonMouseClicked(evt);
            }
        });

        InformationButton.setText("Information");
        InformationButton.setMaximumSize(new java.awt.Dimension(120, 23));
        InformationButton.setMinimumSize(new java.awt.Dimension(120, 23));
        InformationButton.setPreferredSize(new java.awt.Dimension(93, 23));
        InformationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InformationButtonMouseClicked(evt);
            }
        });

        OptionsButton.setText("Options");
        OptionsButton.setMaximumSize(new java.awt.Dimension(120, 23));
        OptionsButton.setMinimumSize(new java.awt.Dimension(120, 23));
        OptionsButton.setPreferredSize(new java.awt.Dimension(93, 23));
        OptionsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OptionsButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(SinglePlayerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MultiPlayerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InformationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OptionsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(313, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(39, 39, 39)
                .addComponent(SinglePlayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MultiPlayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InformationButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OptionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SinglePlayerButtonMouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_SinglePlayerButtonMouseClicked
        //call controller's singlePlayerSelected method
        controller.singlePlayerSelected();
    }//GEN-LAST:event_SinglePlayerButtonMouseClicked

    private void MultiPlayerButtonMouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_MultiPlayerButtonMouseClicked
        //call controller's multiplayerSelected method
        controller.multiplayerSelected();
    }//GEN-LAST:event_MultiPlayerButtonMouseClicked

    private void InformationButtonMouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_InformationButtonMouseClicked
        //call controller's showInstructions method
        controller.showInstructions();
    }//GEN-LAST:event_InformationButtonMouseClicked

    private void OptionsButtonMouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_OptionsButtonMouseClicked
        //call controller's showOptions method
        controller.showOptions();
    }//GEN-LAST:event_OptionsButtonMouseClicked

    /**
     * Version-latenightpizzaparty
     * @param args the command line arguments method parameter
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        // Just in case...
        try
        {
            // Iterate over this set
            for (javax.swing.UIManager.LookAndFeelInfo info
                    : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                // Guard against this
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(IntroScreen.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(IntroScreen.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(IntroScreen.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(IntroScreen.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new IntroScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InformationButton;
    private javax.swing.JButton MultiPlayerButton;
    private javax.swing.JButton OptionsButton;
    private javax.swing.JButton SinglePlayerButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
